### PR TITLE
Invoicing for authorize request, sepa mandate id parameter and critical typo fix 

### PR DESCRIPTION
**Pull request by mcbuckets**

### CODE REVIEW

**Comment by judgej** [comment]
Thanks. Could you merge in from the latest master branch to fix the merge conflicts? I think that critical typo may already be fixed in there, so it should be a straight forward merge.

**Comment by mcbuckets** [comment]
Is that possible? I think since commits are pushed to upstream you have to resolve them. I tried with one more commit but it doesn't work

**Comment by judgej** [comment]
Yes 'tis easy :-)

If you are using the command line, set up a remote to this repo (if you don't already have one) then do a pull from it into your repo:

    pull thisremote master

Then result any merge conflicts if there are any, and push back to your master repo. That's it - the PR will reflect all those changes automatically.

**Comment by judgej** [comment]
It's not always easy to visualise just where you are, but you can often pull from any repo that shares a history, and it will be merged. The advantage of you doing it, is that you can make sure it works as you expect with the master branch of repo it will be merged into.

**Comment by mcbuckets** [comment]
Thanks, i created new pull request

**Pull request closed without merging**
