### PR TITLE
add parameter financingtype

### PR DESCRIPTION
**Pull request by mmokros-pr**
add Parameter "financingtype" for ShopServerAuthorizeRequest

### CODE REVIEW

**Comment by judgej** [comment]
Thanks. I was just looking at whether this would be any more than adding a parameter.

The `financingtype` is also used by the Client and Frontend APIs, so it may be worth moving the setter and getter to the `AbstractRequest` so it's available across the board. Each has different sets of permitted values though.

`financingtype` is also listed as needing to go into the hash calculation in some parts of the documentation (though it is a little ambiguous). That probably won't show up in the Server API though, as that doesn't need a hash, all being back-end.

**Comment by mmokros-pr** [comment]
Hey Jason,
sure Client and Frontend APIs should use it too. I can move the methods to the `AbstractRequest`

**Comment by judgej** [comment]
Cool, thanks. Let me know when that is done, and I'll merge. The hash may need fixing, but this will get you started in the meantime.

**Comment by mmokros-pr** [comment]
done :-)

**Comment by judgej** [comment]
Merged. Thank you.

I'd like to try it out with one of the other APIs before tagging this as a release, just to check the hash works.

**Comment by judgej** [comment]
I seem to be able to put any valid or invalid value in that field on all three APIs without the test gateway complaining. It does object if I add it to the hash though.

So, is it working for you, i.e. actually doing the job? Or is it being ignored?

**Comment by mmokros-pr** [comment]
Hey Jason,

the changes are working for me. I can create payolution debit payment without any problems. Thank you for merging.

**Comment by judgej** [comment]
Thanks. I'll make the release (2.2.2) official.

**Pull request merged**
